//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Контраагенты.
    /// </summary>
    // *** Start programmer edit section *** (Контраагенты CustomAttributes)

    // *** End programmer edit section *** (Контраагенты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КонтраагентыE", new string[] {
            "Контрагент as \'Контрагент\'"})]
    [View("КонтраагентыL", new string[] {
            "Контрагент as \'Контрагент\'"})]
    public class Контраагенты : ICSSoft.STORMNET.DataObject
    {
        
        private string fКонтрагент;
        
        // *** Start programmer edit section *** (Контраагенты CustomMembers)

        // *** End programmer edit section *** (Контраагенты CustomMembers)

        
        /// <summary>
        /// Контрагент.
        /// </summary>
        // *** Start programmer edit section *** (Контраагенты.Контрагент CustomAttributes)

        // *** End programmer edit section *** (Контраагенты.Контрагент CustomAttributes)
        [StrLen(255)]
        public virtual string Контрагент
        {
            get
            {
                // *** Start programmer edit section *** (Контраагенты.Контрагент Get start)

                // *** End programmer edit section *** (Контраагенты.Контрагент Get start)
                string result = this.fКонтрагент;
                // *** Start programmer edit section *** (Контраагенты.Контрагент Get end)

                // *** End programmer edit section *** (Контраагенты.Контрагент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Контраагенты.Контрагент Set start)

                // *** End programmer edit section *** (Контраагенты.Контрагент Set start)
                this.fКонтрагент = value;
                // *** Start programmer edit section *** (Контраагенты.Контрагент Set end)

                // *** End programmer edit section *** (Контраагенты.Контрагент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КонтраагентыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтраагентыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтраагентыE", typeof(IIS.Test.Контраагенты));
                }
            }
            
            /// <summary>
            /// "КонтраагентыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КонтраагентыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КонтраагентыL", typeof(IIS.Test.Контраагенты));
                }
            }
        }
    }
}
