//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Номенкалтура.
    /// </summary>
    // *** Start programmer edit section *** (Номенкалтура CustomAttributes)

    // *** End programmer edit section *** (Номенкалтура CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НоменкалтураE", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "Контраагенты as \'Контраагенты\'",
            "Контраагенты.Контрагент as \'Контрагент\'"}, Hidden=new string[] {
            "Контраагенты.Контрагент"})]
    [MasterViewDefineAttribute("НоменкалтураE", "Контраагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("НоменкалтураL", new string[] {
            "Номенклатура as \'Номенклатура\'",
            "Контраагенты.Контрагент as \'Контрагент\'"})]
    public class Номенкалтура : ICSSoft.STORMNET.DataObject
    {
        
        private string fНоменклатура;
        
        private IIS.Test.Контраагенты fКонтраагенты;
        
        // *** Start programmer edit section *** (Номенкалтура CustomMembers)

        // *** End programmer edit section *** (Номенкалтура CustomMembers)

        
        /// <summary>
        /// Номенклатура.
        /// </summary>
        // *** Start programmer edit section *** (Номенкалтура.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (Номенкалтура.Номенклатура CustomAttributes)
        [StrLen(255)]
        public virtual string Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (Номенкалтура.Номенклатура Get start)

                // *** End programmer edit section *** (Номенкалтура.Номенклатура Get start)
                string result = this.fНоменклатура;
                // *** Start programmer edit section *** (Номенкалтура.Номенклатура Get end)

                // *** End programmer edit section *** (Номенкалтура.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенкалтура.Номенклатура Set start)

                // *** End programmer edit section *** (Номенкалтура.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (Номенкалтура.Номенклатура Set end)

                // *** End programmer edit section *** (Номенкалтура.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// Номенкалтура.
        /// </summary>
        // *** Start programmer edit section *** (Номенкалтура.Контраагенты CustomAttributes)

        // *** End programmer edit section *** (Номенкалтура.Контраагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контраагенты"})]
        [NotNull()]
        public virtual IIS.Test.Контраагенты Контраагенты
        {
            get
            {
                // *** Start programmer edit section *** (Номенкалтура.Контраагенты Get start)

                // *** End programmer edit section *** (Номенкалтура.Контраагенты Get start)
                IIS.Test.Контраагенты result = this.fКонтраагенты;
                // *** Start programmer edit section *** (Номенкалтура.Контраагенты Get end)

                // *** End programmer edit section *** (Номенкалтура.Контраагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Номенкалтура.Контраагенты Set start)

                // *** End programmer edit section *** (Номенкалтура.Контраагенты Set start)
                this.fКонтраагенты = value;
                // *** Start programmer edit section *** (Номенкалтура.Контраагенты Set end)

                // *** End programmer edit section *** (Номенкалтура.Контраагенты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НоменкалтураE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменкалтураE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменкалтураE", typeof(IIS.Test.Номенкалтура));
                }
            }
            
            /// <summary>
            /// "НоменкалтураL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НоменкалтураL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НоменкалтураL", typeof(IIS.Test.Номенкалтура));
                }
            }
        }
    }
}
