//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тест.
    /// </summary>
    // *** Start programmer edit section *** (Тест CustomAttributes)

    // *** End programmer edit section *** (Тест CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТестE", new string[] {
            "Цена as \'Цена\'",
            "Номенкалтура as \'Номенкалтура\'",
            "Номенкалтура.Номенклатура as \'Номенклатура\'",
            "Номенкалтура.Контраагенты as \'Контраагенты\'",
            "Номенкалтура.Контраагенты.Контрагент as \'Контраагенты\'"}, Hidden=new string[] {
            "Номенкалтура.Номенклатура"})]
    [MasterViewDefineAttribute("ТестE", "Номенкалтура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    [View("ТестL", new string[] {
            "Цена as \'Цена\'",
            "Номенкалтура.Номенклатура as \'Номенклатура\'"})]
    public class Тест : ICSSoft.STORMNET.DataObject
    {
        
        private int fЦена;
        
        private IIS.Test.Номенкалтура fНоменкалтура;
        
        // *** Start programmer edit section *** (Тест CustomMembers)

        // *** End programmer edit section *** (Тест CustomMembers)

        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Тест.Цена CustomAttributes)

        // *** End programmer edit section *** (Тест.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (Тест.Цена Get start)

                // *** End programmer edit section *** (Тест.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (Тест.Цена Get end)

                // *** End programmer edit section *** (Тест.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тест.Цена Set start)

                // *** End programmer edit section *** (Тест.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Тест.Цена Set end)

                // *** End programmer edit section *** (Тест.Цена Set end)
            }
        }
        
        /// <summary>
        /// Тест.
        /// </summary>
        // *** Start programmer edit section *** (Тест.Номенкалтура CustomAttributes)

        // *** End programmer edit section *** (Тест.Номенкалтура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенкалтура"})]
        [NotNull()]
        public virtual IIS.Test.Номенкалтура Номенкалтура
        {
            get
            {
                // *** Start programmer edit section *** (Тест.Номенкалтура Get start)

                // *** End programmer edit section *** (Тест.Номенкалтура Get start)
                IIS.Test.Номенкалтура result = this.fНоменкалтура;
                // *** Start programmer edit section *** (Тест.Номенкалтура Get end)

                // *** End programmer edit section *** (Тест.Номенкалтура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Тест.Номенкалтура Set start)

                // *** End programmer edit section *** (Тест.Номенкалтура Set start)
                this.fНоменкалтура = value;
                // *** Start programmer edit section *** (Тест.Номенкалтура Set end)

                // *** End programmer edit section *** (Тест.Номенкалтура Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТестE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТестE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТестE", typeof(IIS.Test.Тест));
                }
            }
            
            /// <summary>
            /// "ТестL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТестL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТестL", typeof(IIS.Test.Тест));
                }
            }
        }
    }
}
